CREATE SEQUENCE IF NOT EXISTS locations_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS sessions_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS users_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE locations
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    latitude  DOUBLE PRECISION                         NOT NULL,
    longitude DOUBLE PRECISION                         NOT NULL,
    name      VARCHAR(255)                             NOT NULL,
    userId    INTEGER                                  NOT NULL,
    CONSTRAINT locations_pkey PRIMARY KEY (id)
);

CREATE TABLE sessions
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    userId    INTEGER                                  NOT NULL,
    expiresAt TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    CONSTRAINT sessions_pkey PRIMARY KEY (id)
);


CREATE TABLE users
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    login    VARCHAR(255)                             NOT NULL,
    password VARCHAR(255)                             NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uq_users_login  UNIQUE (login);

ALTER TABLE sessions
    ADD CONSTRAINT fk_session_userId FOREIGN KEY (userId) REFERENCES users (id) ON DELETE NO ACTION;

ALTER TABLE locations
    ADD CONSTRAINT fk_locations_userId FOREIGN KEY (userId) REFERENCES users (id) ON DELETE NO ACTION;